apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: people-monitor
  name: people-monitor
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: /q/metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: people