kind: GrafanaDatasource
apiVersion: grafana.integreatly.org/v1beta1
metadata:
  name: thanos-querier-datasource
  namespace: ${USER_PROJECT_NAMESPACE}
spec:
  datasource:
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      httpHeaderName1: 'Authorization'
#      customQueryParameters: 'namespace=${USER_PROJECT_NAMESPACE}' # when filtering by namespace
    secureJsonData:
      httpHeaderValue1: 'Bearer ${GRAFANA_SA_BEARER_TOKEN}'
    name: Cluster Thanos Querier
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
#    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9092' #use this port when filtering by namespace
  instanceSelector:
    matchLabels:
      dashboards: grafana-a
      folders: grafana-a
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
