{
 "title": "Quarkus Service Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{cluster=\"\", namespace=\"user1-project\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=\"user1-project\", workload=\"people\", workload_type=\"deploymentconfig\"}\n) by (pod)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Converted Names",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nameconvert_process_counter_total{service=\"people\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Converter Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_bytes_written_count{service=\"people\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Greetings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "greeting_hello_counter_total{service=\"people\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}